name: tabs
description: Tabs is a material app to keep tabs of money being spent.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: any
  path: any
  sqflite: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/psans.ttf